### ISSUE TITLE
 Infura API keys should not be publicly accessible (0sp)

### ISSUE THREAD

**Issue by hynek-urban** [windingtree/wt-read-api#148]
Currently, our Infura API key is publicly accessible within certain configurations (config/*.js). That should not be the case. The following steps need to be done:

1. Find a way to provide this key in a protected way, e.g. using encrypted variables in Travis.
2. Get a non-compromised Infura API key and utilize it according to point 1.
3. Disable the original API key.

**Comment by JirkaChadima** [comment]
`1.` resolved in 2b976b765706e7598aca1248939f77c31d185925

**Comment by JirkaChadima** [comment]
Changes in Infura API access: https://mailchi.mp/51860dca76fb/update-to-the-infura-api-authentication?e=1715cad57f

**Comment by czervenka** [comment]
waits for https://github.com/windingtree/wt-write-api/issues/23 to be solved

**Comment by JirkaChadima** [comment]
Fixed in 4babf6d0973eab48e3d4f672387c52c35a5f06ab
