### ISSUE TITLE
swagger docs are pointing to a bad environment

### ISSUE THREAD

**Issue by JirkaChadima** [windingtree/wt-read-api#155]
https://playground-api.windingtree.com/docs/ points to demo-api.windingtree.com

**Comment by hynek-urban** [comment]
@JirkaChadima Isn't this a duplicate of #147 that has already been fixed? Or is this something else?

**Comment by JirkaChadima** [comment]
This is directly in the rendered swagger docs, I think the endpoint is defined in docs/swagger.yaml and it's hardcoded to demo.

**Comment by hynek-urban** [comment]
Fixed in `develop`; it will be deployed with the next release.
