### ISSUE TITLE
Validate upstream data

### ISSUE THREAD

**Issue by hynek-urban** [windingtree/wt-read-api#183]
Right now, the read API works as a thin proxy between the user and the on-chain/off-chain data. No validation of the data is performed before returning it to the user.

I believe we should perform validation wrt. hotel structure, otherwise the API does not conform to its own specification (by potentially returning data that do not fit the swagger definition at all).

**Comment by JirkaChadima** [comment]
I agree, and https://github.com/windingtree/wiki/issues/73 is part of the solution. All of the ecosystem should revolve around a fixed and declared data structure.

**Comment by JirkaChadima** [comment]
Closed for now in #198
