### ISSUE TITLE
Accessing hotel on endpoint /hotels/<hotel-id>/ leads to gateway error

### ISSUE THREAD

**Issue by czervenka** [windingtree/wt-read-api#229]
The hotel is accessible on {{/hotels/<hotel-id>}} but not on {{/hotels/<hotel-id>/}}. The server should either redirect to proper address if we follow [Robustness principle](https://en.m.wikipedia.org/wiki/Robustness_principle) or return {{404 Not found}} http response indicating that the address does not exist or ``400 Bad request`` indicating invalid hotel id. It returns {{502 Bad gateway}}.

**Comment by JirkaChadima** [comment]
Will be fixed in the next release.
