### ISSUE TITLE
Missing fields=spokenLanguages in documentation

### ISSUE THREAD

**Issue by czervenka** [windingtree/wt-read-api#238]
To show spoken languages I need to add fields=spokenLanguages. There is no such possible value in the [documentation](https://developers.windingtree.com/apis/wt-read-api.html#/default/get_hotels__hotelId_).

Expected behavior: `spokenLanguages` in the documentation in possible `fields` parametr value or (preferably) `spokenLanguages` returned by default.

**Comment by JirkaChadima** [comment]
Fixed in next release
